### ISSUE TITLE
Use of input param in NBACards query in Graphql

### ISSUE THREAD

**Issue by PacoASBH** [script-money/sorare-nba-lineup-tool#1]
Hello,

I was looking to get some NBA datas from Sorare API and I found your excellent project. :)

Can you explain me please how do you use the "input" param in NBACards query please ?
How do you use the id that you retrieved from currentSportsUser function ?

![Screenshot2](https://user-images.githubusercontent.com/121180654/208961123-ba819362-ef2a-4694-8c96-fff6e26883a0.PNG)
![Screenshot3](https://user-images.githubusercontent.com/121180654/208961352-fd666734-f81b-4a3d-88d2-d14fbda576ca.PNG)

Thanks a lot !

Paco

**Comment by script-money** [comment]
Check "Variables"

<img width="741" alt="Screenshot 2022-12-23 at 12 44 00" src="https://user-images.githubusercontent.com/74860630/209272462-5cf6f773-31c9-4a7e-9784-4eee4becddc2.png">

**Comment by PacoASBH** [comment]
Ok thanks, I had issues with escape character. It's works now. :)
